services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pcxp-api
    ports:
      - "8000:8000"
    environment:
      PYTHONDONTWRITEBYTECODE: "1"
      PYTHONUNBUFFERED: "1"
    volumes:
      - ./models:/app/models
      - ./data:/app/data:ro
