stages:
  train:
    cmd: python python/train.py
    deps:
      - python/train.py
      - python/ml_pipeline.py
      - data/PCXP/train
      - data/PCXP/test
    outs:
      - models/model.pth:
          cache: true
  evaluate:
    cmd: python python/predict.py
    deps:
      - python/predict.py
      - python/ml_pipeline.py
      - data/PCXP/test
      - models/model.pth
